/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.time.Instant;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for Databasechangelog.
 */
public class DatabasechangelogDTO {
    public String id;
    public String author;
    public String filename;
    public Instant dateexecuted;
    public Integer orderexecuted;
    public String exectype;
    public String md5sum;
    public String description;
    public String comments;
    public String tag;
    public String liquibase;
    public String contexts;
    public String labels;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null && !id.isEmpty();
    }
}